services:
  app:
    container_name: ryama-v2
    build:
      context: .
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - type: volume
        source: node_modules
        target: /app/node_modules
      - type: bind
        source: ./
        target: /app
    command: >
      /bin/sh -c '
      npm run priup &&
      npm run dev
      '
  db:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    env_file:
      - .env
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind
  db:
