version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: db
        target: /var/lib/postgresql/data
    env_file:
      - .env
  app: &app
    container_name: ryama-v2
    build:
      context: .
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - type: volume
        source: node_modules
        target: /workspace/node_modules
      - type: bind
        source: .
        target: /workspace
        consistency: cached
    command: >
      sh -c "
      npm run priup &&
      npm run dev
      "
    depends_on:
      - db
  studio:
    container_name: studio
    <<: *app
    command: npx prisma studio
    ports:
      - '5555:5555'
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind
  postgres:
