services:
  app:
    container_name: ryama-v2
    build:
      context: .
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: ["npm","run","dev"]
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  node_modules:
